#!/bin/bash

SLEEPTIME=${1:-60}

while true; do
    eval $(xdotool getmouselocation --shell)
    
    IDLETIME=$(xprintidle)
    IDLETIME=$(($IDLETIME/1000))
    if [[ $IDLETIME -gt $SLEEPTIME ]]; then
        xdotool mousemove $X $((Y-1))
    fi

    sleep $SLEEPTIME
done
